import { LAYOUT_APP } from "../../shared/layout";

export const routes = [
  {
    layout: LAYOUT_APP,
    exact: true,
    name: 'Настройки проекта',
    path: '/project-settings',
    order: 0,
    hidden: false,
    load: () => import('./view/projectSettings'),
    resolvers: [],
  },  {
    layout: LAYOUT_APP,
    exact: true,
    name: 'Список проектов',
    path: '/project-list',
    order: 0,
    hidden: false,
    load: () => import('./view/projectList'),
    resolvers: [],
  }, {
    layout: LAYOUT_APP,
    exact: true,
    name: 'Создание проекта',
    path: '/project-create',
    order: 0,
    hidden: false,
    load: () => import('./view/projectCreate'),
    resolvers: [],
  },{
    layout: LAYOUT_APP,
    exact: true,
    name: 'Список ревизий',
    path: '/revision-list',
    order: 0,
    hidden: false,
    load: () => import('./view/revisionList'),
    resolvers: [],
  },{
    layout: LAYOUT_APP,
    exact: true,
    name: 'Настройки документа',
    path: '/document-settings',
    order: 0,
    hidden: false,
    load: () => import('./view/documentSettings'),
    resolvers: [],
  },{
    layout: LAYOUT_APP,
    exact: true,
    name: 'Настройки документа',
    path: '/project/:projectid',
    order: 0,
    hidden: false,
    load: () => import('./view/projectEditor'),
    resolvers: [],
  },
];
