export default {
  "level": 0,
  "name": "I. ТЗ - RK-186-344",
  "toggled": true,
  "loading": false,
  "id": 0,
  "childcell": "37cea22b074140c6ac32a660",
  "children": [{
    "id": "37cea22b074140c6ac32a660",
    "name": "Padberg, Wisozk and Ziemann",
    "verify": "checked",
    "prevcell": null,
    "nextcell": "1f0a81ce83d64e288be246da",
    "parent": null,
    "childcell": null,
    "is_head": true,
    "content": {"number": "56804", "__typename": "Block"},
    "approvalstatus": "",
    "__typename": "Cell",
    "level": 1
  }, {
    "id": "1f0a81ce83d64e288be246da",
    "name": "Denesik, Jakubowski and Corwin",
    "verify": "checked",
    "prevcell": null,
    "nextcell": "b61f32d704224d56ad51e832",
    "parent": null,
    "childcell": "13b04f9fdc1b459cac39b09f",
    "is_head": true,
    "content": {"number": "97962", "__typename": "Block"},
    "approvalstatus": "",
    "__typename": "Cell",
    "level": null,
    "children": [],
    "toggled": true,
    "loading": true,
    "active": true
  }, {
    "id": "b61f32d704224d56ad51e832",
    "name": "Corwin Group",
    "verify": "not_checked",
    "prevcell": null,
    "nextcell": null,
    "parent": null,
    "childcell": "7106b116344742f98e17afca",
    "is_head": true,
    "content": {"number": "3595", "__typename": "Block"},
    "approvalstatus": "",
    "__typename": "Cell",
    "level": null,
    "children": [],
    "toggled": false,
    "loading": true,
    "active": false
  }, {
    "id": "13b04f9fdc1b459cac39b09f",
    "name": "Dickinson and Sons",
    "verify": "checked",
    "prevcell": null,
    "nextcell": "22c8af8bd711480fb67a80c1",
    "parent": null,
    "childcell": "4e2f747338a949e9b0dbc05a",
    "is_head": true,
    "content": {"number": "40304", "__typename": "Block"},
    "approvalstatus": "",
    "__typename": "Cell",
    "level": null,
    "children": [],
    "toggled": false,
    "loading": true,
    "active": false
  }, {
    "id": "22c8af8bd711480fb67a80c1",
    "name": "Heller, Koch and Cummings",
    "verify": "checked",
    "prevcell": null,
    "nextcell": "4505d4ec726440a2ae36d7b8",
    "parent": null,
    "childcell": null,
    "is_head": true,
    "content": {"number": "28006", "__typename": "Block"},
    "approvalstatus": "",
    "__typename": "Cell",
    "level": null
  }, {
    "id": "4505d4ec726440a2ae36d7b8",
    "name": "Jast - Strosin",
    "verify": "checked",
    "prevcell": null,
    "nextcell": null,
    "parent": null,
    "childcell": null,
    "is_head": true,
    "content": {"number": "58931", "__typename": "Block"},
    "approvalstatus": "",
    "__typename": "Cell",
    "level": null
  }],
  "active": true
}
