import { LAYOUT_APP, LAYOUT_AUTH } from '../../shared/layout';

export const routes = [
  {
    layout: LAYOUT_AUTH,
    exact: false,
    name: 'Вход',
    path: '/',
    order: 0,
    hidden: false,
    load: () => import('./view/login'),
    resolvers: [],
  },
  {
    layout: LAYOUT_AUTH,
    exact: false,
    name: 'Вход',
    path: '/login',
    order: 0,
    hidden: false,
    load: () => import(/* webpackChunkName: 'userLogin' */ './view/login'),
    resolvers: [],
  },
  {
    layout: LAYOUT_AUTH,
    exact: true,
    name: 'Регистрация',
    path: '/login',
    order: 0,
    hidden: false,
    load: () => import(/* webpackChunkName: 'userRegistration' */ './view/registration'),
    resolvers: [],
  },
  {
    layout: LAYOUT_AUTH,
    exact: true,
    name: 'Восстановление пароля',
    path: '/password-recovery',
    order: 0,
    hidden: false,
    load: () => import(/* webpackChunkName: 'userPasswordRecovery' */ './view/passwordRecovery'),
    resolvers: [],
  },
  {
    layout: LAYOUT_APP,
    exact: true,
    name: 'Личный кабинет',
    path: '/profile',
    order: 0,
    hidden: false,
    load: () => import(/* webpackChunkName: 'userProfile'  */ './view/profile/user'),
    resolvers: [],
  },
  {
    layout: LAYOUT_APP,
    exact: true,
    name: 'Личный кабинет',
    path: '/profileAdmin',
    order: 0,
    hidden: false,
    load: () => import(/* webpackChunkName: 'userProfile'  */ './view/profile/admin'),
    resolvers: [],
  },
];

export default routes;
