import { LAYOUT_APP, LAYOUT_AUTH } from '../../shared/layout';
import { ROLE_ADMIN, ROLE_USER } from '../../shared/roles';

export const routes = [
  {
    layout: LAYOUT_AUTH,
    exact: true,
    name: 'Вход',
    path: '/',
    order: 0,
    hidden: false,
    load: () => import(/* webpackChunkName: 'userLogin' */ './view/login'),
    resolvers: [],
  },
  {
    layout: LAYOUT_AUTH,
    exact: true,
    name: 'Вход',
    path: '/login',
    order: 0,
    hidden: false,
    load: () => import(/* webpackChunkName: 'userLogin' */ './view/login'),
    resolvers: [],
  },
  {
    layout: LAYOUT_AUTH,
    exact: true,
    name: 'Регистрация',
    path: '/registration',
    order: 0,
    hidden: false,
    load: () => import(/* webpackChunkName: 'userRegistration' */ './view/registration'),
    resolvers: [],
  },
  {
    layout: LAYOUT_AUTH,
    exact: true,
    name: 'Восстановление пароля',
    path: '/password-recovery',
    order: 0,
    hidden: false,
    load: () => import(/* webpackChunkName: 'userPasswordRecovery' */ './view/passwordRecovery'),
    resolvers: [],
  },
  {
    layout: LAYOUT_APP,
    exact: true,
    name: 'Личный кабинет',
    path: '/profile',
    order: 0,
    hidden: false,
    load: () => import(/* webpackChunkName: 'userProfile'  */ './view/profile'),
    roles: [ROLE_ADMIN, ROLE_USER],
  },
];
