export const COMMENTS_READ_AUTHOR = 'COMMENTS_READ_AUTHOR';
export const COMMENTS_READ_PARTNER = 'COMMENTS_READ_PARTNER';
export const COMMENTS_WRITE = 'COMMENTS_WRITE';
export const COMMENTS_HIDE = 'COMMENTS_HIDE';
